export const FAVORITES_LIST_REQUEST = "FAVORITES_LIST_REQUEST";
export const FAVORITES_LIST_SUCCESS = "FAVORITES_LIST_SUCCESS";
export const FAVORITES_LIST_FAIL = "FAVORITES_LIST_FAIL";


export const COMPANY_LIST_REQUEST = "COMPANY_LIST_REQUEST";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_LIST_FAIL = "COMPANY_LIST_FAIL";

export const FAVORITES_CREATE_REQUEST = "FAVORITES_CREATE_REQUEST";
export const FAVORITES_CREATE_SUCCESS = "LEAVE_REQUEST_CREATE_SUCCESS";
export const FAVORITES_CREATE_FAIL = "FAVORITES_CREATE_FAIL";

export const FAVORITES_DELETE_REQUEST = "FAVORITES_DELETE_REQUEST";
export const FAVORITES_DELETE_SUCCESS = "FAVORITES_DELETE_SUCCESS";
export const FAVORITES_DELETE_FAIL = "FAVORITES_DELETE_FAIL";
