export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";


export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_RESET_REQUEST = "USER_RESET_REQUEST";
export const USER_RESET_REQUEST_SUCCESS = "USER_RESET_REQUEST_SUCCESS";
export const USER_RESET_REQUEST_FAIL = "USER_RESET_REQUEST_FAIL";

export const USER_ACTIVATE_REQUEST = "USER_ACTIVATE_REQUEST";
export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS";
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL";

export const USER_CONFIRM_RESET_REQUEST = "USER_CONFIRM_RESET_REQUEST";
export const USER_CONFIRM_RESET_SUCCESS = "USER_CONFIRM_RESET_SUCCESS";
export const USER_CONFIRM_RESET_FAIL = "USER_CONFIRM_RESET_FAIL";